services:
  - type: web
    name: chatterbox-tts
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /api/health
    plan: starter
    region: oregon
    branch: main
